### ISSUE TITLE
ffsll and ffs not found!

### ISSUE THREAD

**Issue by JohnGrubba** [efrantar/twophase#18]
Here the full error code:
C:\Users\Besitzer\Desktop\rob-twophase>make
g++  -std=c++11 -lpthread -O3 -DF5  -c -o src/coord.o src/coord.cpp
src/coord.cpp: In function 'int coord::get_combperm(const int*, int, int)':
src/coord.cpp:72:21: error: 'ffs' was not declared in this scope
   72 |     int min_cubie = ffs(mask) - 1;
      |                     ^~~
src/coord.cpp: In function 'void coord::init_move(uint16_t (*)[18], int, int (*)(const cubie::cube&), void (*)(cubie::cube&, int), void (*)(const cubie::cube&, const cubie::cube&, cubie::cube&), bool)':
src/coord.cpp:233:19: error: 'ffsll' was not declared in this scope
  233 |           int m = ffsll(moves) - 1;
      |                   ^~~~~
make: *** [<builtin>: src/coord.o] Error 1

**Comment by JohnGrubba** [comment]
Please Help!

**Comment by JohnGrubba** [comment]
I also tried including string.h it didnt work!
I am Using Windows 10 Pro and Visual Studio Code!
i enter make in the command line and it says 
C:\Users\Besitzer\Desktop\rob-twophase>make
g++ -std=c++11 -lpthread -O3 -DF5 -c -o src/coord.o src/coord.cpp
src/coord.cpp: In function 'int coord::get_combperm(const int*, int, int)':
src/coord.cpp:72:21: error: 'ffs' was not declared in this scope
72 | int min_cubie = ffs(mask) - 1;
| ^~~
src/coord.cpp: In function 'void coord::init_move(uint16_t ()[18], int, int ()(const cubie::cube&), void ()(cubie::cube&, int), void ()(const cubie::cube&, const cubie::cube&, cubie::cube&), bool)':
src/coord.cpp:233:19: error: 'ffsll' was not declared in this scope
233 | int m = ffsll(moves) - 1;
| ^~~~~
make: *** [: src/coord.o] Error 1

**Comment by efrantar** [comment]
`ffs()` and `ffsll()` are very fast low-level Linux specific functions that don't exist on Windows. It should be possible to replace those calls with Windows equivalents, however you may also run into issues with `pthread` which is a Unix threading library.

Instead I would suggest trying to compile & run this program from the Linux subsystem on Windows 10, or if that fails in a virtual machine (there it will certainly work).

I only use Linux myself, so I unfortunately cannot help you with Windows problems. Hence, I also do not have any intentions on making this program natively compatible with Windows. Sorry.

**Comment by JohnGrubba** [comment]
Ok thanks!
